# TODO sql需要重构

date = str(20221122)

# 资产表
sql1 = "SELECT * FROM FV_ASSET_FUND t WHERE t.ACCTING_UNIT='344' AND t.BUSI_DATE='20220806'"
# 持仓表
sql2 = "SELECT * FROM  FV_HOLD_FUND t WHERE t.POSITION_CODE ='00.32.01.99.01.HOLDER5.*.CNY.HSHG328677115' AND t.BUSI_DATE ='20220801'"
# 科目余额-转资产
sql = (
    "SELECT t.BUSIDATE ,t.SUBJECTCODE ,t.bendamt,t.endqty FROM fin_daybalance t \
WHERE t.SETTUNIT ='POC01' AND t.BUSIDATE ="
    + date
    + " ORDER BY t.BUSIDATE"
)
# 估值表-转持仓
sql3 = (
    "SELECT substr(SUBJECTCODE, 7, 2), t.SUBJECTCODE, t.STKCODE, t.mktprice, t.qty, t.BCOST, t.BMKTVAL, t.BADDVAL FROM val_valuation t \
WHERE t.SETTUNIT ='POC01' AND t.BUSIDATE ="
    + date
    + " AND t.STKCODE IS NOT null"
)
# 流水表
sql4 = "SELECT * FROM FV_CLEAR t WHERE t.ACCTING_UNIT ='A001'"
sql5 = f"SELECT * FROM FV_CLEAR t WHERE t.ACCTING_UNIT ='POC01' and t.busi_flow_no ='202210281810188239705739302'; "


# 存款合约
sql6 = "SELECT * FROM FV_CONTRACT t WHERE t.ACCTING_UNIT ='POC01' AND t.BUSI_DATE ='20221101'"



pgddl ='''
-- fvs.fv_clear definition

-- Drop table

-- DROP TABLE fvs.fv_clear;

CREATE TABLE fvs.fv_clear (
	busi_flow_no varchar(32) NOT NULL,
	create_date int4 NOT NULL,
	accting_unit varchar(32) NOT NULL,
	asset_unit varchar(32) NULL,
	hold_unit varchar(32) NULL DEFAULT '0'::character varying,
	strategy_comb varchar(32) NULL DEFAULT '0'::character varying,
	scheme_id varchar(32) NULL DEFAULT '0'::character varying,
	stk_acct varchar(32) NULL,
	remain_mark varchar(2) NULL,
	fnc_tool_class varchar(2) NULL,
	position_direction bpchar(2) NULL,
	position_type bpchar(2) NULL,
	listed_circulate_situa varchar(2) NULL,
	ccy_code varchar(4) NULL,
	exch_rate numeric(16, 8) NULL,
	busi_class_code varchar(4) NULL,
	busi_type varchar(16) NOT NULL,
	clear_spd numeric(22) NULL,
	scr_id varchar(64) NULL,
	clear_date int4 NULL,
	trd_date int4 NULL,
	match_amt numeric(22, 4) NULL,
	match_price numeric(22, 8) NULL,
	match_qty numeric(22, 6) NULL,
	clear_amt numeric(22, 4) NULL,
	intr_amt numeric(22, 4) NULL,
	tax_fee_amt numeric(22, 6) NULL,
	fee_yhs numeric(22, 4) NULL,
	fee_ghf numeric(22, 4) NULL,
	fee_jgf numeric(22, 6) NULL,
	fee_jiesf numeric(22, 4) NULL,
	fee_jsf numeric(22, 4) NULL,
	fee_qtf_use numeric(22, 4) NULL,
	fee_sxf numeric(22, 4) NULL,
	fee_zgf numeric(22, 4) NULL,
	risk_amt numeric(22, 4) NULL,
	net_commission numeric(22, 6) NULL,
	other_amt1 numeric(22, 6) NULL,
	other_amt2 numeric(22, 6) NULL,
	other_amt3 numeric(22, 6) NULL,
	other_qty1 numeric(22, 6) NULL,
	sum_group_flow_no varchar(32) NULL,
	capital_acct varchar(32) NULL,
	trustee_seat varchar(16) NULL,
	apply_way bpchar(2) NULL,
	rel_virtual_accting_unit varchar(32) NULL,
	deposit_bank_code varchar(8) NULL,
	bank_acct varchar(64) NULL,
	provision_acct varchar(64) NULL,
	broker_code varchar(32) NULL,
	trd_seat varchar(16) NULL,
	special_busi_code varchar(20) NULL,
	buy_sell_flag varchar(2) NULL,
	ord_direction varchar(2) NULL,
	invest_class varchar(2) NULL,
	market_code varchar(3) NULL,
	register_org_code varchar(16) NULL,
	scr_code varchar(64) NULL,
	scr_name varchar(128) NULL,
	scr_type varchar(4) NULL,
	scr_id2 varchar(64) NULL,
	contract_code varchar(32) NULL,
	ex_right_date int4 NULL,
	register_date int4 NULL,
	other_date int4 NULL,
	trd_apply_id varchar(32) NULL,
	settle_id varchar(90) NULL,
	settle_code varchar(32) NULL,
	match_id varchar(32) NULL,
	match_time numeric(22) NULL,
	face_value numeric(22, 2) NULL,
	yield numeric(22, 8) NULL,
	settle_method bpchar(1) NULL,
	settle_type bpchar(1) NULL,
	rival_code varchar(32) NULL,
	scr_change_direction bpchar(1) NULL,
	scr_real_settle_date int4 NULL,
	scr_settle_date int4 NULL,
	capital_change_direction bpchar(1) NULL,
	capital_real_settle_date int4 NULL,
	capital_settle_date int4 NULL,
	busi_rel_flow_no varchar(32) NULL,
	pair_status bpchar(1) NULL,
	pair_type bpchar(1) NULL,
	calc_fee_flag bpchar(1) NULL,
	clear_time varchar(2) NULL,
	trader_id numeric(22) NULL,
	invest_manager numeric(22) NULL,
	ins_sno varchar(32) NULL,
	ins_mod_sno numeric(22) NULL,
	ord_sno varchar(32) NULL,
	match_sno varchar(32) NULL,
	permit_apply_way varchar(2) NULL DEFAULT NULL::character varying,
	intf_code varchar(64) NULL,
	remark varchar(128) NULL,
	flow_status bpchar(1) NULL,
	data_src varchar(64) NULL,
	syn_sno numeric(22) NULL,
	mod_date_time varchar(32) NULL,
	CONSTRAINT pk_fv_clear PRIMARY KEY (busi_flow_no)
);

'''


oracleddl ='''

-- FVS_N.FV_CLEAR definition

CREATE TABLE "FVS_N"."FV_CLEAR" 
   (	"CLEAR_FLOW_NO" VARCHAR2(32) NOT NULL ENABLE, 
	"CREATE_DATE" NUMBER(*,0) NOT NULL ENABLE, 
	"ACCTING_UNIT" VARCHAR2(32) NOT NULL ENABLE, 
	"STRATEGY_COMB" VARCHAR2(32), 
	"PERMIT_APPLY_WAY" VARCHAR2(2), 
	"ASSET_UNIT" VARCHAR2(32), 
	"HOLD_UNIT" VARCHAR2(32), 
	"CAPITAL_ACCT" VARCHAR2(32), 
	"STK_ACCT" VARCHAR2(32), 
	"TRUSTEE_SEAT" VARCHAR2(16), 
	"REMAIN_MARK" VARCHAR2(2), 
	"FNC_TOOL_CLASS" VARCHAR2(2), 
	"POSITION_DIRECTION" CHAR(2), 
	"POSITION_TYPE" CHAR(2), 
	"LISTED_CIRCULATE_SITUA" VARCHAR2(2), 
	"APPLY_WAY" CHAR(2), 
	"REL_VIRTUAL_ACCTING_UNIT" VARCHAR2(32), 
	"CCY_CODE" CHAR(3), 
	"EXCH_RATE" NUMBER(16,8), 
	"DEPOSIT_BANK_CODE" VARCHAR2(8), 
	"BANK_ACCT" VARCHAR2(64), 
	"PROVISION_ACCT" VARCHAR2(64), 
	"BROKER_CODE" VARCHAR2(32), 
	"TRD_SEAT" VARCHAR2(16), 
	"BUSI_CLASS_CODE" VARCHAR2(4), 
	"BUSI_TYPE" VARCHAR2(16), 
	"SPECIAL_BUSI_CODE" VARCHAR2(20), 
	"CLEAR_SPD" NUMBER(22,0), 
	"BUY_SELL_FLAG" VARCHAR2(2), 
	"ORD_DIRECTION" VARCHAR2(2), 
	"INVEST_CLASS" VARCHAR2(2), 
	"SCR_ID" VARCHAR2(64), 
	"MARKET_CODE" VARCHAR2(3), 
	"REGISTER_ORG_CODE" VARCHAR2(16), 
	"SCR_CODE" VARCHAR2(64), 
	"SCR_NAME" VARCHAR2(128), 
	"SCR_TYPE" VARCHAR2(4), 
	"SCR_ID2" VARCHAR2(64), 
	"CONTRACT_CODE" VARCHAR2(32), 
	"CLEAR_DATE" NUMBER(*,0), 
	"TRD_DATE" NUMBER(*,0), 
	"EX_RIGHT_DATE" NUMBER(*,0), 
	"REGISTER_DATE" NUMBER(*,0), 
	"OTHER_DATE" NUMBER(*,0), 
	"TRD_APPLY_ID" VARCHAR2(32), 
	"SETTLE_ID" VARCHAR2(90), 
	"SETTLE_CODE" VARCHAR2(32), 
	"MATCH_ID" VARCHAR2(32), 
	"MATCH_TIME" NUMBER(22,0), 
	"MATCH_AMT" NUMBER(22,4), 
	"MATCH_PRICE" NUMBER(22,8), 
	"MATCH_QTY" NUMBER(22,2), 
	"CLEAR_AMT" NUMBER(22,4), 
	"INTR_AMT" NUMBER(22,4), 
	"TAX_FEE_AMT" NUMBER(22,6), 
	"FEE_YHS" NUMBER(22,4), 
	"FEE_GHF" NUMBER(22,4), 
	"FEE_JGF" NUMBER(22,6), 
	"FEE_JIESF" NUMBER(22,4), 
	"FEE_JSF" NUMBER(22,4), 
	"FEE_QTF_USE" NUMBER(22,4), 
	"FEE_SXF" NUMBER(22,4), 
	"FEE_ZGF" NUMBER(22,4), 
	"RISK_AMT" NUMBER(22,4), 
	"NET_COMMISSION" NUMBER(22,6), 
	"OTHER_AMT1" NUMBER(22,6), 
	"OTHER_AMT2" NUMBER(22,6), 
	"OTHER_AMT3" NUMBER(22,6), 
	"OTHER_QTY1" NUMBER(22,6), 
	"FACE_VALUE" NUMBER(22,2), 
	"YIELD" NUMBER(22,8), 
	"SETTLE_METHOD" CHAR(1), 
	"SETTLE_TYPE" CHAR(1), 
	"RIVAL_CODE" VARCHAR2(32), 
	"SCR_CHANGE_DIRECTION" CHAR(1), 
	"SCR_REAL_SETTLE_DATE" NUMBER(*,0), 
	"SCR_SETTLE_DATE" NUMBER(*,0), 
	"CAPITAL_CHANGE_DIRECTION" CHAR(1), 
	"CAPITAL_REAL_SETTLE_DATE" NUMBER(*,0), 
	"CAPITAL_SETTLE_DATE" NUMBER(*,0), 
	"BUSI_REL_FLOW_NO" VARCHAR2(32), 
	"PAIR_STATUS" CHAR(1), 
	"PAIR_TYPE" CHAR(1), 
	"CALC_FEE_FLAG" CHAR(1), 
	"CLEAR_TIME" VARCHAR2(2), 
	"TRADER_ID" NUMBER(22,0), 
	"INVEST_MANAGER" NUMBER(22,0), 
	"INSTR_ID" VARCHAR2(32), 
	"ORD_SNO" VARCHAR2(32), 
	"INTF_CODE" VARCHAR2(64), 
	"REMARK" VARCHAR2(128), 
	"FLOW_STATUS" CHAR(1), 
	"DATA_SRC" VARCHAR2(64), 
	"SYN_SNO" NUMBER(22,0), 
	"CREATE_OPER_ID" NUMBER(*,0), 
	"CREATE_DATE_TIME" VARCHAR2(32), 
	"MOD_OPER_ID" NUMBER(*,0), 
	"MOD_DATE_TIME" VARCHAR2(32), 
	"SCHEME_ID" VARCHAR2(32) DEFAULT ' ' NOT NULL ENABLE, 
	 CONSTRAINT "PK_FV_CLEAR" PRIMARY KEY ("CLEAR_FLOW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FVS_N_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FVS_N_TBS" ;

CREATE UNIQUE INDEX "FVS_N"."PK_FV_CLEAR" ON "FVS_N"."FV_CLEAR" ("CLEAR_FLOW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FVS_N_TBS" ;
 
  CREATE INDEX "FVS_N"."FV_CLEAR_NO_DATE_IDX" ON "FVS_N"."FV_CLEAR" ("ACCTING_UNIT", "CREATE_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FVS_N_TBS" ;
 
  CREATE INDEX "FVS_N"."FV_CLEAR_IDX_2" ON "FVS_N"."FV_CLEAR" ("CREATE_DATE", "DATA_SRC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FVS_N_TBS" ;

COMMENT ON TABLE FVS_N.FV_CLEAR IS 'fv_清算流水表';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CLEAR_FLOW_NO IS '清算流水号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CREATE_DATE IS '开始日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.ACCTING_UNIT IS '核算单元';
COMMENT ON COLUMN FVS_N.FV_CLEAR.STRATEGY_COMB IS '策略组合';
COMMENT ON COLUMN FVS_N.FV_CLEAR.PERMIT_APPLY_WAY IS '申赎通道';
COMMENT ON COLUMN FVS_N.FV_CLEAR.ASSET_UNIT IS '资产单元';
COMMENT ON COLUMN FVS_N.FV_CLEAR.HOLD_UNIT IS '持仓单元';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CAPITAL_ACCT IS '资金账号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.STK_ACCT IS '证券账号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TRUSTEE_SEAT IS '托管席位';
COMMENT ON COLUMN FVS_N.FV_CLEAR.REMAIN_MARK IS '存量标识';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FNC_TOOL_CLASS IS '金融工具分类';
COMMENT ON COLUMN FVS_N.FV_CLEAR.POSITION_DIRECTION IS '持仓方向';
COMMENT ON COLUMN FVS_N.FV_CLEAR.POSITION_TYPE IS '持仓类型';
COMMENT ON COLUMN FVS_N.FV_CLEAR.LISTED_CIRCULATE_SITUA IS '流通性质';
COMMENT ON COLUMN FVS_N.FV_CLEAR.APPLY_WAY IS '股份来源';
COMMENT ON COLUMN FVS_N.FV_CLEAR.REL_VIRTUAL_ACCTING_UNIT IS '关联虚拟核算单元';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CCY_CODE IS '币种代码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.EXCH_RATE IS '汇率';
COMMENT ON COLUMN FVS_N.FV_CLEAR.DEPOSIT_BANK_CODE IS '存款银行编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BANK_ACCT IS '银行账号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.PROVISION_ACCT IS '备付金账号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BROKER_CODE IS '经纪商编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TRD_SEAT IS '交易席位';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BUSI_CLASS_CODE IS '业务分类编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BUSI_TYPE IS '业务类型';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SPECIAL_BUSI_CODE IS '特殊业务编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CLEAR_SPD IS '清算速度';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BUY_SELL_FLAG IS '买卖标志';
COMMENT ON COLUMN FVS_N.FV_CLEAR.ORD_DIRECTION IS '委托方向';
COMMENT ON COLUMN FVS_N.FV_CLEAR.INVEST_CLASS IS '投资分类';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_ID IS '证券内码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MARKET_CODE IS '交易市场';
COMMENT ON COLUMN FVS_N.FV_CLEAR.REGISTER_ORG_CODE IS '登记机构代码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_CODE IS '证券代码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_NAME IS '证券名称';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_TYPE IS '证券类型';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_ID2 IS '证券内码2';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CONTRACT_CODE IS '合约编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CLEAR_DATE IS '清算日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TRD_DATE IS '交易日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.EX_RIGHT_DATE IS '除权日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.REGISTER_DATE IS '登记日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.OTHER_DATE IS '其他日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TRD_APPLY_ID IS '交易申请编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SETTLE_ID IS '交收编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SETTLE_CODE IS '结算编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MATCH_ID IS '成交编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MATCH_TIME IS '成交时间';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MATCH_AMT IS '成交金额';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MATCH_PRICE IS '成交价格';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MATCH_QTY IS '成交数量';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CLEAR_AMT IS '清算金额';
COMMENT ON COLUMN FVS_N.FV_CLEAR.INTR_AMT IS '利息金额';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TAX_FEE_AMT IS '税费金额';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_YHS IS '印花税';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_GHF IS '过户费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_JGF IS '监管费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_JIESF IS '结算费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_JSF IS '经手费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_QTF_USE IS '其他费用';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_SXF IS '手续费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FEE_ZGF IS '证管费';
COMMENT ON COLUMN FVS_N.FV_CLEAR.RISK_AMT IS '风险金额';
COMMENT ON COLUMN FVS_N.FV_CLEAR.NET_COMMISSION IS '净佣金';
COMMENT ON COLUMN FVS_N.FV_CLEAR.OTHER_AMT1 IS '其他金额1';
COMMENT ON COLUMN FVS_N.FV_CLEAR.OTHER_AMT2 IS '其他金额2';
COMMENT ON COLUMN FVS_N.FV_CLEAR.OTHER_AMT3 IS '其他金额3';
COMMENT ON COLUMN FVS_N.FV_CLEAR.OTHER_QTY1 IS '其他数量1';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FACE_VALUE IS '面值';
COMMENT ON COLUMN FVS_N.FV_CLEAR.YIELD IS '收益率';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SETTLE_METHOD IS '结算方式';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SETTLE_TYPE IS '交收类型';
COMMENT ON COLUMN FVS_N.FV_CLEAR.RIVAL_CODE IS '交易对手编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_CHANGE_DIRECTION IS '证券变化方向';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_REAL_SETTLE_DATE IS '证券实际交收日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SCR_SETTLE_DATE IS '证券交收日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CAPITAL_CHANGE_DIRECTION IS '资金变化方向';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CAPITAL_REAL_SETTLE_DATE IS '资金实际交收日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CAPITAL_SETTLE_DATE IS '资金交收日期';
COMMENT ON COLUMN FVS_N.FV_CLEAR.BUSI_REL_FLOW_NO IS '业务关联流水号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.PAIR_STATUS IS '配对状态';
COMMENT ON COLUMN FVS_N.FV_CLEAR.PAIR_TYPE IS '配对类型';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CALC_FEE_FLAG IS '计费标识';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CLEAR_TIME IS '清算时点';
COMMENT ON COLUMN FVS_N.FV_CLEAR.TRADER_ID IS '交易员编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.INVEST_MANAGER IS '投资经理编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.INSTR_ID IS '指令编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.ORD_SNO IS '委托序号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.INTF_CODE IS '接口编码';
COMMENT ON COLUMN FVS_N.FV_CLEAR.REMARK IS '备注';
COMMENT ON COLUMN FVS_N.FV_CLEAR.FLOW_STATUS IS '流水状态';
COMMENT ON COLUMN FVS_N.FV_CLEAR.DATA_SRC IS '数据来源';
COMMENT ON COLUMN FVS_N.FV_CLEAR.SYN_SNO IS '同步序号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CREATE_OPER_ID IS '创建人编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.CREATE_DATE_TIME IS '创建日期时间';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MOD_OPER_ID IS '更新人编号';
COMMENT ON COLUMN FVS_N.FV_CLEAR.MOD_DATE_TIME IS '更新日期时间';

'''